### PR TITLE
ZNTA-1457: Update release scripts for 4.0.0

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-1457

Brief:
Removed: 
  * zanata-build-pr: Pull request builder, no nolonger relevant.
  * zanata-version-get-latest: Get latest version of a module, use detect_module_version in zanata-functions instead.

Important programs:
 * `zanata-functions`: Host various bash functions which are required by other programs.
 * `zanata-maven-release`: Release Zanata in Maven (Sonatype). It also do pre-release tasks, like update Zanata dependency (e.g. zanata-assets), pull translation, and prepend the release-notes.md
 * `zanata-version-update`: Update the zanata-dependencies. It is invoked by `zanata-maven-release`
 * `zanata-translation-pull`: Pull, validate, and commit Translation
 * `zanata-release-branching`: Branch the release and legacy for big release.
 * `zanata-release-notes-prepend `:  Prepend or update release-notes for given version.
   

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-scripts/9)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 9 of 18 files at r1.
Review status: 8 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-overlay-build, line 139 at r1](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KYvhqjang4raxFgVTAl:-KYvhqjang4raxFgVTAm:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-scripts/blob/471d65e0fb8c3befe78d60f423808d7c1c666f73/zanata-overlay-build#L139)):*
> ```
> print_status -t "download dependency" -s "Start"
> OverlayWorkDir=${WORK_ROOT}/overlay
> mkdir -p ${OverlayWorkDir}
> ```

:+1: 

---

*[ZanataScriptsCommon.pm, line 142 at r1](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KYvfgNyj85izICDRcsF:-KYvfgNyj85izICDRcsG:bhgaf7v) ([raw file](https://github.com/zanata/zanata-scripts/blob/471d65e0fb8c3befe78d60f423808d7c1c666f73/ZanataScriptsCommon.pm#L142)):*
> ```Perl6
> 
> 	die "artifactory_username is not defined, "
> 	. "please put 'gitub_username=<USERNAME>' in $zanataScriptsIni"
> ```

should this be artifactory_username?

---

*[ZanataScriptsCommon.pm, line 146 at r1](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KYvfkgV-PanRpx4wHnn:-KYvfkgV-PanRpx4wHno:bt2otvo) ([raw file](https://github.com/zanata/zanata-scripts/blob/471d65e0fb8c3befe78d60f423808d7c1c666f73/ZanataScriptsCommon.pm#L146)):*
> ```Perl6
> 
> 	die "artifactory_token is not defined, "
> 	. "please put 'gitub_token=<TOKEN>' in $zanataScriptsIni"
> ```

should this be artifactory_token?

---

*[ZanataScriptsCommon.pm, line 150 at r1](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KYvi4gC0ARug3TZ4I9S:-KYvi4gC0ARug3TZ4I9T:bdz09o) ([raw file](https://github.com/zanata/zanata-scripts/blob/471d65e0fb8c3befe78d60f423808d7c1c666f73/ZanataScriptsCommon.pm#L150)):*
> ```Perl6
> }
> 
> sub artifactory_logined_rest_response {
> ```

Can we give this a better name? Maybe get_artifactory_rest_response?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by definite** [comment]
Review status: 8 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[ZanataScriptsCommon.pm, line 150 at r1](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KYvi4gC0ARug3TZ4I9S:-KYw6wrMbBDMdk3by6vY:b1ciauj) ([raw file](https://github.com/zanata/zanata-scripts/blob/471d65e0fb8c3befe78d60f423808d7c1c666f73/ZanataScriptsCommon.pm#L150)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can we give this a better name? Maybe get_artifactory_rest_response?
</blockquote></details>

Perhaps the artifactory related function should be moved to the program that actually use artifactory. 

I made a wrong assumption that many programs require this function. But in the end, only one need this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by seanf** [comment]
Reviewed 8 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[zanata-functions, line 451 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lalh62UY2dM6_qaM:-KZ4lalh62UY2dM6_qaN:b-w0yjgw) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-functions#L451)):*
> ```
> 	    ;;
> 	*server)
> 	    echo "zanata-server"
> ```

Can we get rid of some of these bits?

---

*[zanata-functions, line 490 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lgEFUJGhLtq9QmRk:-KZ4lgEFUJGhLtq9QmRl:b-k2pczf) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-functions#L490)):*
> ```
> 	    ;;
> 	*server)
> 	    echo "server"
> ```

Here too.

---

*[zanata-maven-release, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4ls9T_ru3TlEsp0hb:-KZ4ls9T_ru3TlEsp0hc:b-46rpwh) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-maven-release#L21)):*
> ```
> ###
> ###     -P: Working on pull request branch
> ###         pr-<artifactId>-<version>
> ```

For a release? How does that work?

---

*[zanata-maven-release, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lmhvuq9pMOpTwQp3:-KZ4lmhvuq9pMOpTwQp4:bwl1vqe) ([raw file](https://github.com/zanata/zanata-scripts/blob/33ab70a577024ee5023723f8b03c74d138172047/zanata-maven-release#L22)):*
> ```
> ###
> ###     -n:
> ###         Dry-run
> ```

We should keep dry run mode.

---

*[zanata-maven-release, line 177 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4l131ZHkNW-_NLn4G:-KZ4l131ZHkNW-_NLn4H:b-w3gnfa) ([raw file](https://github.com/zanata/zanata-scripts/blob/33ab70a577024ee5023723f8b03c74d138172047/zanata-maven-release#L177)):*
> ```
> 	    ;;
> 	n )
> 	    DryRunMode=1
> ```

Don't get rid of dry run mode.

---

*[zanata-version-update, line 13 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kIfN1-eWOtDEuf48:-KZ4kIfN1-eWOtDEuf49:bihqzwg) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L13)):*
> ```
> ###
> ### ARGUMENTS
> ###     <module>: module name like zanata-platform
> ```

Other than zanata-platform, what could it be? I'm beginning to think we aren't taking advantage of the simpler structure, now that zanata-platform contains (virtually) all the Maven modules.

I think we should have tried harder to make maven-release-plugin work for us. These scripts are too complex to maintain as a team.

---

*[zanata-version-update, line 26 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kcDDtiydKxWwBdgE:-KZ4kcDDtiydKxWwBdgF:bh9w3wf) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L26)):*
> ```
> ###
> ###     -j: Jenkins mode.
> ###         This assumes that current directory is <module> work directory.
> ```

Huh? What does that mean, and why is it called Jenkins mode?

---

*[zanata-version-update, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4k5tgxiNJqsKcjl89:-KZ4k5tgxiNJqsKcjl8A:bewcn9c) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L60)):*
> ```
> while getopts "hBjnp" opt;do
>     case $opt in
> 	h )
> ```

I think you should avoid using tabs in these scripts. They never display consistently.

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-KZ4jxl-Qgf7FdrOoNvO:bkgnlpd) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
> ```
> 	read -p "### Are the change looks alright? Press [Ctrl-C] to break, [Enter] to continue"
>     fi
>     git commit -a -m "chore(version): Update Zanata dependencies"
> ```

I don't trust the -a option. What's wrong with the **/pom.xml?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by definite** [comment]
Review status: 10 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

*[zanata-functions, line 451 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lalh62UY2dM6_qaM:-KZK2N8NX2vB6zsiZh_3:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-functions#L451)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Can we get rid of some of these bits?
</blockquote></details>

Done.

---

*[zanata-functions, line 490 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lgEFUJGhLtq9QmRk:-KZK2MZKb6e-IaWKqWtF:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-functions#L490)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Here too.
</blockquote></details>

Done.

---

*[zanata-maven-release, line 21 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4ls9T_ru3TlEsp0hb:-KZJik1gIl-WBXX16vuq:b-ol41sr) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-maven-release#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

For a release? How does that work?
</blockquote></details>

Basically just branch checkout the branch pr-platform-4.0.0 and do the release on that branch.
Using that mode, you can see the translation and release-notes change easily.
However,  if no translation and release-notes change, sometime you may see "empty" merge that looks like nothing have been changed.

For example, when releasing 4.0.0-rc-1, then version change from 4.0.0-SNAPSHOT -> 4.0.0-rc-1 -> 4.0.0-SNAPSHOT.

---

*[zanata-maven-release, line 22 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4lmhvuq9pMOpTwQp3:-KZK2JtHG5ebQHmxykSh:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/33ab70a577024ee5023723f8b03c74d138172047/zanata-maven-release#L22)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

We should keep dry run mode.
</blockquote></details>

Done.

---

*[zanata-maven-release, line 177 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4l131ZHkNW-_NLn4G:-KZK2JAJpnNAj1asSWkx:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/33ab70a577024ee5023723f8b03c74d138172047/zanata-maven-release#L177)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Don't get rid of dry run mode.
</blockquote></details>

Done.

---

*[zanata-version-update, line 13 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kIfN1-eWOtDEuf48:-KZJOrEHE4gWyU4qrdMJ:b-3oocht) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L13)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Other than zanata-platform, what could it be? I'm beginning to think we aren't taking advantage of the simpler structure, now that zanata-platform contains (virtually) all the Maven modules.

I think we should have tried harder to make maven-release-plugin work for us. These scripts are too complex to maintain as a team.
</blockquote></details>

To name a few: zanata-assets, jgettext, openprops. I am still not certain that we won't ever have individual module (repo) again.

I did spent many days trying to making release plugin work., but failed.
Didn't Yow 2015 continuous delivery trend suggest we use versions  instead of release plugin?

---

*[zanata-version-update, line 26 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kcDDtiydKxWwBdgE:-KZJS6oV34VDz9Yg-djT:b-ihlt6a) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L26)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Huh? What does that mean, and why is it called Jenkins mode?
</blockquote></details>

Because normal (without -j) mode with do the automatic checkout and change directory , which is convenient when you execute the program manually.
jenkins does this for you.
The reason I did not move all this to jenkins is because of GPG key and kerberos.

---

*[zanata-version-update, line 60 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4k5tgxiNJqsKcjl89:-KZK2GerqCViHHI3eXUV:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L60)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I think you should avoid using tabs in these scripts. They never display consistently.
</blockquote></details>

Done.

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-KZJUfEwImNOPP03IiZW:bys61b0) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I don't trust the -a option. What's wrong with the **/pom.xml?
</blockquote></details>

**/pom.xml also matches something like:

server/zanata-war/target/war/work/org.zanata/gwt-editor/META-INF/maven/org.zanata/gwt-editor/pom.xml
server/zanata-test-war/target/war/work/org.zanata/zanata-war/META-INF/maven/org.zanata/zanata-war/pom.xml

Those are not meant to be in source tree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by seanf** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[zanata-artifact-m2repo, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka10uvEJo68P3oFNDUV:-Ka10uvEJo68P3oFNDUW:b-xy9j7m) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-artifact-m2repo#L11)):*
> ```
> ### DESCRIPTION
> ###     This program produces artifact list from m2 repo
> ###     By default, it uses ${HOME}/.m2/repository
> ```

That doesn't seem like a good default, since we don't want to start uploading whatever random artifacts happen to be in that directory.

I suggest enabling that with another option, and not having a default repo.

---

*[zanata-artifact-m2repo, line 43 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka11OQLrt-mbzsgfyzA:-Ka11OQLrt-mbzsgfyzB:byzyzg0) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-artifact-m2repo#L43)):*
> ```
> ###         zanata-maven-release will download the artifacts
> ###         to /tmp/zanata/maven-central-release-repo
> 	l )
> ```

`-l` might be a good option for the local `~/.m2/repository`, in which case I would suggest `-t` for this temp dir, or better still, avoid hard-coding knowledge of that location into this script entirely.

---

*[zanata-maven-release, line 84 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka1-vlXFWvWT7RGECWz:-Ka1-vlYJyAi_2JRwdyx:b-ro37i3) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L84)):*
> ```
>     if [[ $DryRunMode -eq 0 ]];then
>         [[ -z $StagingRepositoryBuffer ]] &&\
>             failed $EXIT_FATAL_FAIL " Failed to found artifacts in ${NEXUS_STAGING_PLUGIN}:rc-list"
> ```

found -> find

---

*[zanata-maven-release, line 98 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka105vCYglyeSs_7zpC:-Ka105vDsxQRIdb5TYhG:bemk543) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L98)):*
> ```
>         print_status " StagingRepositoryId=$StagingRepositoryId StagingRepositoryState=$StagingRepositoryState"
>     else
>         print_status " [Dry-Run] No StagingRepositoryId, because artifacts not deployed"
> ```

maybe "because artifact deployment is skipped"?

---

*[zanata-maven-release, line 151 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka10OPQFUXhSi4mennM:-Ka10OPQFUXhSi4mennN:blwf7wz) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L151)):*
> ```
> ###     -j: Jenkins mode.
> ###         This assumes that current directory is <module> work directory.
> ###         and correct branch is checked out.
> ```

As in the other script, this option needs a more meaningful name.

---

*[zanata-version-update, line 26 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kcDDtiydKxWwBdgE:-Ka0zwac9gpuowEygAMK:b-4c6xbm) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L26)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Because normal (without -j) mode with do the automatic checkout and change directory , which is convenient when you execute the program manually.
jenkins does this for you.
The reason I did not move all this to jenkins is because of GPG key and kerberos.
</blockquote></details>

It sounds like "jenkins mode" or "just use current directory" should be the default, and the git checkout feature is more of a developer convenience.

Either way, "Jenkins mode" is not very meaningful.

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-Ka0y2Av01vh2ConbtzI:bjf2c87) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

**/pom.xml also matches something like:

server/zanata-war/target/war/work/org.zanata/gwt-editor/META-INF/maven/org.zanata/gwt-editor/pom.xml
server/zanata-test-war/target/war/work/org.zanata/zanata-war/META-INF/maven/org.zanata/zanata-war/pom.xml

Those are not meant to be in source tree.
</blockquote></details>

You should be able to use `git add **/pom.xml && git commit -m ...` `git add` will skip over any `.gitignore`d files.

But `git commit -a` should skip any new files, so I guess it's not too bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[zanata-artifact-m2repo, line 11 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka10uvEJo68P3oFNDUV:-Ka5MpLBF55buTSHnxQP:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-artifact-m2repo#L11)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

That doesn't seem like a good default, since we don't want to start uploading whatever random artifacts happen to be in that directory.

I suggest enabling that with another option, and not having a default repo.
</blockquote></details>

Done.

---

*[zanata-artifact-m2repo, line 43 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka11OQLrt-mbzsgfyzA:-Ka5Mo9wA28MYip465pl:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-artifact-m2repo#L43)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

`-l` might be a good option for the local `~/.m2/repository`, in which case I would suggest `-t` for this temp dir, or better still, avoid hard-coding knowledge of that location into this script entirely.
</blockquote></details>

Done.

---

*[zanata-maven-release, line 84 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka1-vlXFWvWT7RGECWz:-Ka5Mn1QyVPdF75kSsCZ:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L84)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

found -> find
</blockquote></details>

Done.

---

*[zanata-maven-release, line 98 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka105vCYglyeSs_7zpC:-Ka5MmJCMBXWoWt1zTrY:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L98)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

maybe "because artifact deployment is skipped"?
</blockquote></details>

Done.

---

*[zanata-maven-release, line 151 at r3](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka10OPQFUXhSi4mennM:-Ka5MlXlsEJ3mD9QXK0F:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d0f4d368968e9f74ed55d758edd7057b6f4b02a8/zanata-maven-release#L151)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

As in the other script, this option needs a more meaningful name.
</blockquote></details>

Done.

---

*[zanata-version-update, line 26 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4kcDDtiydKxWwBdgE:-Ka5Mji4B_HY2qbsjVM_:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L26)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

It sounds like "jenkins mode" or "just use current directory" should be the default, and the git checkout feature is more of a developer convenience.

Either way, "Jenkins mode" is not very meaningful.
</blockquote></details>

Done.

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-Ka5Lfm2PKAZTVMdHdCy:b-tnua64) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

You should be able to use `git add **/pom.xml && git commit -m ...` `git add` will skip over any `.gitignore`d files.

But `git commit -a` should skip any new files, so I guess it's not too bad.
</blockquote></details>

`git add **/pom.xml` will add files even if they are in `.gitignore`. 
However, according to `man git add`, we need to quote the `**`, i.e.
 `git add "**/pom.xml"` is the way to go. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by seanf** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[zanata-release-branching, line 44 at r4](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka5W27s6BtfXDSzVUh6:-Ka5W27s6BtfXDSzVUh7:bleyal8) ([raw file](https://github.com/zanata/zanata-scripts/blob/d3689018203d269c2341311db054cd331113ea6c/zanata-release-branching#L44)):*
> ```
>             ;;
> ###
> ###     -j: Just use current directory
> ```

Just use current directory (no git checkout)

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-Ka5V6q0yKz6OrRcbspy:b-i1zaat) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

`git add **/pom.xml` will add files even if they are in `.gitignore`. 
However, according to `man git add`, we need to quote the `**`, i.e.
 `git add "**/pom.xml"` is the way to go. 
</blockquote></details>

In my tests (using a shell which understands globstar), git add **/pom.xml works, with some warnings about the ignored directories.

But `git add '**/pom.xml'` doesn't add ./pom.xml, so I suspect git doesn't understand '**' in the globstar sense.

We'd better go back to `git commit -a` I suppose.

---

*[zanata-version-update, line 25 at r4](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka5Vye-rudGdoR5F0JZ:-Ka5Vye0wV3eEER9AHou:bleyal8) ([raw file](https://github.com/zanata/zanata-scripts/blob/d3689018203d269c2341311db054cd331113ea6c/zanata-version-update#L25)):*
> ```
> ###         It will NOT ask question and proceed with default choice.
> ###
> ###     -j: Just use current directory.
> ```

Just use current directory (no git checkout)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by definite** [comment]
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[zanata-release-branching, line 44 at r4](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka5W27s6BtfXDSzVUh6:-Ka5bpb7AmE7L_YGawuk:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d3689018203d269c2341311db054cd331113ea6c/zanata-release-branching#L44)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Just use current directory (no git checkout)
</blockquote></details>

Done.

---

*[zanata-version-update, line 111 at r2](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-KZ4jxkz2wHrp9VggFmc:-Ka5bnf-ctI7JdjI1mLX:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/52df2699c413e8cfde114b7dc300518cf2e8f010/zanata-version-update#L111)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

In my tests (using a shell which understands globstar), git add **/pom.xml works, with some warnings about the ignored directories.

But `git add '**/pom.xml'` doesn't add ./pom.xml, so I suspect git doesn't understand '**' in the globstar sense.

We'd better go back to `git commit -a` I suppose.
</blockquote></details>

Done.

---

*[zanata-version-update, line 25 at r4](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-Ka5Vye-rudGdoR5F0JZ:-Ka5bm3IVhlaWEiZTkVZ:b-896fix) ([raw file](https://github.com/zanata/zanata-scripts/blob/d3689018203d269c2341311db054cd331113ea6c/zanata-version-update#L25)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Just use current directory (no git checkout)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-:-Ka5flshaPJtJWCBN92N:bnfp4nl)*

**Comment by definite** [comment]
-(Awaiting review) +Reviewed 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-scripts/9#-:-Ka60s6tqhbrVJARssjn:b-nl5gbj)*

**Pull request merged**
