### PR TITLE
zanata-nexus-staging scripts

### PR DESCRIPTION
**Pull request by definite**
Scripts to automate (as much as possible) the release to sonatype.
Run ./zanata-nexus-staging to get usage

### CODE REVIEW

**Comment by seanf** [comment]
I wish we could put this much effort into configuring the maven-release-plugin correctly, to make it work with Sonatype OSS automatically.  

If the script is running `mvn release` (and thus pushing to github), I think that should be made very obvious in the script name, and at runtime before the script does anything.  Other than that, I can't see anything immediately wrong with the script, but I have never done a release this way.  @huangp might be the better reviewer.

**Comment by alex-sl-eng** [comment]
@definite do you think if release scripts can be in its own package? like `release` dir ?

**Comment by alex-sl-eng** [comment]
@definite given now there's not much script for nexus-staging, lets just keep it in root dir.

**Comment by alex-sl-eng** [comment]
:+1:

**Pull request merged**
